### ISSUE TITLE
Update loader 

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/currencee#15]
Preferred new loader. 

```css
.loaderContainer {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

.loader {
  width: 25px;
  height: 25px;
  border: 4px solid #333;
  border-bottom-color: transparent;
  border-radius: 50%;
  display: inline-block;
  box-sizing: border-box;
  animation: rotation 0.4s linear infinite;
}
```
